### ISSUE TITLE
Active Directory RFC2307 optional support

### ISSUE THREAD

**Issue by MFlyer** [rockstor/rockstor-core#1263]
Linked to this forum thread [https://forum.rockstor.com/t/rockstor-active-directory-ad-integration-implementation/561/7](https://forum.rockstor.com/t/rockstor-active-directory-ad-integration-implementation/561/7)

Add option in AD Join to use rfc2307 schema + winbind nss info = rfc2307 (we assume that using schema for UIDS -> rfc2307 for home and shell settings of every user)

Merged @ScarabMonkey fork branch into new one refering issue + one commit

@schakrava do you agree on going on?? It's easy and we leave it as optional (default to rid backend, as actually doing)

**Comment by ScarabMonkey** [comment]
I would like to try it out, but the process for testing code-changes is a bit convoluted at present - will try it out today...

**Comment by MFlyer** [comment]
Hi @ScarabMonkey do you have a testing env or a working env???

First case:
sync your local git repo with modified files than rsync to test env and perform buildout after db migration

Second case:
Not so easy, but possible (**snapshot your VM before proceding!**)
manually edit modified files, perform db migration and build static (for js and jst files) + reboot VM (reboot VM equals buildout for py files)

Flyer

**Comment by ScarabMonkey** [comment]
Successfully built a testing server but for some reason it doesn't seem to be pulling our users from the AD - though it can get the groups. Intriguingly I can use 'net ads user' to list the users but wbinfo gives me nothing.

```
[root@milan samba]# wbinfo --verbose -u
[root@milan samba]# wbinfo --verbose -g
AD\domain computers
....(more groups here)
```

Will do more testing tomorrow

**Comment by ScarabMonkey** [comment]
I have been fiddling with this over the last 2 days and can conistently build a new VM which is only able to get the groups out of our AD, not the Users - even on a base Testing-branch install without any patches.

I can use getent to list the groups on the command-line and this will also list individual AD users ... but not the full list..
```
[root@milan ~]# getent group
root:x:0:
bin:x:1:
daemon:x:2:
sys:x:3:
adm:x:4:
tty:x:5:
disk:x:6:
lp:x:7:
mem:x:8:
kmem:x:9:
wheel:x:10:
cdrom:x:11:
mail:x:12:postfix
man:x:15:
dialout:x:18:nut
floppy:x:19:
games:x:20:
tape:x:30:
video:x:39:
ftp:x:50:
lock:x:54:
audio:x:63:
nobody:x:99:
users:x:100:
avahi-autoipd:x:170:
utmp:x:22:
utempter:x:35:
ssh_keys:x:999:
nginx:x:998:
stapusr:x:156:
stapsys:x:157:
stapdev:x:158:
input:x:997:
systemd-journal:x:190:
systemd-bus-proxy:x:996:
systemd-network:x:995:
dbus:x:81:
rpc:x:32:
polkitd:x:994:
nut:x:57:
cgred:x:993:
docker:x:992:
avahi:x:70:
wbpriv:x:88:
postdrop:x:90:
postfix:x:89:
postgres:x:26:
usbmuxd:x:113:
tss:x:59:
dip:x:40:
chrony:x:991:
ntp:x:38:
rpcuser:x:29:
nfsnobody:x:65534:
sshd:x:74:
fester:x:1000:
AD\winrmremotewmiusers__:x:2000:
AD\domain computers:x:1515:
AD\domain controllers:x:1516:
AD\schema admins:x:1518:
AD\enterprise admins:x:1519:
<snip>
[root@milan ~]# getent passwd
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
<snip - no AD accounts>
[root@milan ~]# getent passwd "AD\merlin"
AD\merlin:*:11195:1513:Merlin Hartley:/home/AD/merlin:/bin/sh
[root@milan ~]#
```

**Comment by MFlyer** [comment]
Hi @ScarabMonkey , can you provide samba logs output??? especially `/var/log/samba/log.winbindd-idmap`. There are 2 possibilities: something is missing on your AD DC or we're missing something (or messing up something). Looking around i found that working with rfc2307 may have samba conf adding other settings (Look at this [Samba 3 Ad Member](http://www.lucasbrasilino.com/blog/linux/centosrhel-samba-3-ad-member-server-setup/#Samba_Member_Server), although it referes to samba 3, and samba official ref too [Samba Docs](https://www.samba.org/samba/docs/man/Samba-HOWTO-Collection/idmapper.html#id2607771) and try to manually modify smb.conf - first thing i would try is adding uid and gid)

**Comment by ScarabMonkey** [comment]
Just to clarify - I am now seeing problems even without the rfc2307 code installed - suspect something strange on my network (though my other rockstor installation is totally fine)

**Comment by ScarabMonkey** [comment]
Just adding more findings relating to users missing (without the patch):

My original Rockstor installation that does see the users is not finding new users added to the AD.
New installations do not see the users in the GUI, but they can successfully use SMB shares and assign permissions from Windows clients (and the files on disk show the correct user)

**Comment by MFlyer** [comment]
Hi @ScarabMonkey, AD users usually are collected with sssd and so does Rockstor - this is what i remember. I don't remember instead if there were samba mods on code. Will check asap

**Comment by MFlyer** [comment]
Hi @ScarabMonkey, looking to my users list from Rockstor it's all fine: I added a new user 2-3 days ago and it's correctly showing in Rockstor.
No changes have been made to samba code since 2-3 months

**Comment by schakrava** [comment]
Just a small clarification that we stopped using sssd and use winbind entirely for AD.

I am unable to test this setup at this point, so your testing will help speed things a bit. so thanks for this active thread!

**Comment by ScarabMonkey** [comment]
I am now failing to build this again due to a URL that it tries to use for the python setuptools - which is incorrect - though I can't find this URL in the code... : https://pypi.python.org/packages/source/s/setuptools/setuptools-20.10.1.zip

**Comment by phillxnet** [comment]
I had this same issue yesterday and it looks like it's at the Pypy end of things. It's working find for me now but affected me yesterday and that was when they updated that packages so I suspect it's a propagation thing. That url is not hard coded in the build system as far as I'm aware, hence the assumption that it's at their end. All I can suggest is thay you wait a bit and see how it goes.
I've changed nothing from yesterday and it now works so bit of a nuasance but should resolve itself in time.
https://pypi.python.org/pypi/setuptools

**Comment by MFlyer** [comment]
Hi all, I confirm @phillxnet - got pypi errors many times while building Rockstor (initially because of my Watchguard settings blocking zips, then again depending on their side)

Flyer

**Comment by ScarabMonkey** [comment]
Yeah, looks like a pypi propagation issue, successfully built it this morning.

**Comment by ScarabMonkey** [comment]
Okay, I can confirm that the rfc2307 fields are indeed being read and I can mount shares and write files which show-up on disk with the correct owners. 
Unfortunately I still can't see the Users on the Rockstor GUI - but I fell this is a local problem as I have the same issue without this patch.

**Comment by MFlyer** [comment]
Hi @ScarabMonkey so you think we can go on with pull request??? :smiley:

**Comment by ScarabMonkey** [comment]
Definitely, it certainly does what it should do to the configuration files.

**Comment by schakrava** [comment]
Fixed by #1265
