### ISSUE TITLE
(t) alt arch causing false positive update available

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2468]
Akin to the following commit:
https://github.com/rockstor/rockstor-core/pull/2462/commits/6d553a879de25c16c50538a9bdbc7290a84c8fee
associated with merged pr:
"move to multi-arch repos from leap 15.4 onwards #2458" #2462
we have a cosmetic bug arising from our move to mult-arch repositories:

Our existing dnf-yum changelog parsing magic ends up flagging an alternative architecture (say aarch64 on an x86_64 install) as a potential update.

I.e.
**Rockstor 4.5.4-0.aarch64, update is available!**
is displayed as an available update but as the changelogs are the same there is not changelog displayed.

This issue is primarily cosmetic as the "zypper up rockstor" command invoked as a result of the "Start Update" will not end up installing the alternative architecture rpm due to it's incompatibility.

It is proposed that we further enhance our dnf-yum changelog 'magic' to filter out this false positive rockstor package update indicator.

**Comment by phillxnet** [comment]
Related but not exactly the same is our indication of an actual update, but showing (cosmetic only) an indication of another arch.
On a 4.5.4-0 with a proposed and actual 4.5.5-0 x86_64 update available in a multi-arch:
![arch-indication-on-x86_64](https://user-images.githubusercontent.com/2521585/213472904-de1909f4-052c-4d04-995a-a3b693d5d354.png)

**Comment by kanecko** [comment]
I am getting the same thing on a 4.5.5-0 x86_64 install as well.

**Comment by phillxnet** [comment]
@kanecko Thanks for the confirmation. Much appreciated.
As indicated in the issue text it's a cosmetic issue but distracting all the same. We have this issue on our next Milestone so should be all good once we reach the next stable release.

**Comment by kanecko** [comment]
Can I press update, even though it states a different arch than what I have installed?
![image](https://user-images.githubusercontent.com/5829467/214808404-dbaaf2f4-f2b1-4242-ba67-88cb0e628c16.png)

**Comment by phillxnet** [comment]
@kanecko Hello there.
Re:

> Can I press update, even though it states a different arch than what I have installed?

You can indeed. If there actually is no update it will simply go through the motions and end up doing nothing, if there is one, it will install it.

We use zypper for the actual updates, and this message comes from our dnf-yum changelog (of as yet uninstalled packages) magic to show the changelog. The problem here is that we have to resource dnf-yum, as zypper has not yet the ability to read changelogs of uninstalled package versions.

**Comment by kanecko** [comment]
If you are sure that this purely a cosmetic bug, and the update will work on different arches, I suggest displaying only the version number without the arch.

**Comment by phillxnet** [comment]
@kanecko Nice idea, but it's an indication of a failure (bug) in our asesment of updates available, via their future changelog. This use to work exactly as intended before we switched to the multi-arch, (a modernisation move) but after was initially triggered by the RPMS in the repo, which was fixed fairly easily. I'd really rather find a fix for the underlying mechanism.

If we cover up the source of the changelog 'trigger' it will only come back to haunt us. I.e. what if one arch gets ahead of another in the rpm builds for what-ever reason. This would lead to spurious update indications that our future selves may find even more obscure given we have obscured some of the debug info.

However, nice work-around if we don't find the time to sort properly. But lets give this a little more brewing time as I'm hoping for some people time from where-ever will emerge and sort this one at source :) .

The nicest fix would be to not have to manage parallel package managers just to get uninstalled Changelog entries, but zypper just doesn't have this capability yet, or at least last time I looked.

**Comment by phillxnet** [comment]
A little more info on how 'other' architectures interfere:
Using an existing installer derived instance (4.5.6-0) subscribed to PRODUCTION testing, via Web-UI, where we have both x86_64 and aarch64 rpm updates to 4.5.7-0. And so we get a reproducer for this issue.

We currently use (for as-yet uninstalled updates to rockstor): `yum changelog 1 rockstor`

and form that, in our new multi-arch repos, there are two intertwined feeds:

```
Last metadata expiration check: 0:16:22 ago on Mon 06 Mar 2023 15:51:54 WET.
allow_vendor_change is disabled. This option is currently not supported for downgrade and distro-sync commands
Listing all changelogs
No match for argument: 1
Changelogs for rockstor-4.5.7-0.aarch64, rockstor-4.5.7-0.x86_64
* Fri Feb 17 00:00:00 2023 Philip Guyton <philip@yewtreeapps.com> - 4.5.7-0
-Bump versions to a 4.5.7 base (RC4) #2496 @phillxnet
-Improve README.md re package licensing, project goals etc #2489 @phillxnet
-Web-UI update to start rockstor-bootstrap.service #2488 @phillxnet @kanecko
-Refactor scrub status parsing to enhance/enable testing #2342 @phillxnet
-Pending 'missing' case issue re btrfs fi show #2311 @phillxnet
-Move Rock-on url default definitions to runtime #2305 @FroggyFlox
```
Note the dual entries on the Changelogs for line: `rockstor-4.5.7-0.aarch64, rockstor-4.5.7-0.x86_64`
Not sure where that '1' element came from. Likely during the transition between older yum on CentOS and then a few upgrade through our days with dnf-yum. For now it's not a problem and looks to fail peacefully.

**Comment by phillxnet** [comment]
## Following on from the last comment --
If we instead do an inline filter/wildcard of our target arch,  `yum changelog 1 rockstor*x86_64` we get:

```
Last metadata expiration check: 0:27:53 ago on Mon 06 Mar 2023 15:51:54 WET.
allow_vendor_change is disabled. This option is currently not supported for downgrade and distro-sync commands
Listing all changelogs
No match for argument: 1
Changelogs for rockstor-4.5.7-0.x86_64
* Fri Feb 17 00:00:00 2023 Philip Guyton <philip@yewtreeapps.com> - 4.5.7-0
-Bump versions to a 4.5.7 base (RC4) #2496 @phillxnet
-Improve README.md re package licensing, project goals etc #2489 @phillxnet
-Web-UI update to start rockstor-bootstrap.service #2488 @phillxnet @kanecko
-Refactor scrub status parsing to enhance/enable testing #2342 @phillxnet
-Pending 'missing' case issue re btrfs fi show #2311 @phillxnet
-Move Rock-on url default definitions to runtime #2305 @FroggyFlox

* Wed Jan 25 00:00:00 2023 Philip Guyton <philip@yewtreeapps.com> - 4.5.6-0
...
```
So we have a likely less confusing Changelogs line:.

**Comment by phillxnet** [comment]
Experimenting now to see if this is all we need.

**Comment by phillxnet** [comment]
The above changelog use is primarily for all other packages. But the same holds true:
`yum changelog all rockstor`

```
Last metadata expiration check: 0:09:15 ago on Mon 06 Mar 2023 16:23:01 WET.
allow_vendor_change is disabled. This option is currently not supported for downgrade and distro-sync commands
Listing all changelogs
No match for argument: all
Changelogs for rockstor-4.5.7-0.aarch64, rockstor-4.5.7-0.x86_64
* Fri Feb 17 00:00:00 2023 Philip Guyton <philip@yewtreeapps.com> - 4.5.7-0
...
```
Again our "all" seems to be bogus but working.

**Comment by phillxnet** [comment]
Working towards pull request now as with a simple additional arch specific wildcard we get:
## After proposed change:
![after-proposed-change](https://user-images.githubusercontent.com/2521585/223176977-50d11552-266d-432e-9d0b-721703eb01dc.png)

**Comment by phillxnet** [comment]
Closing as:
Fixed by #2512

**Comment by Hooverdan96** [comment]
Just to provide a quick post-release update on this issue
I just performed the update from 4.5.7-0 to 4.5.8-0 and after the update it shows the same fake message as observed before:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/35113775/223564322-75627016-680a-4f69-8720-49c6c11dd37f.png">

Main difference to previous behavior is that the change log is now empty. I did a couple of <Ctrl+Shift+R> key combos to refresh, but didn't make a difference.

However, I am happy to report that after a reboot of the system, it now shows correctly that there is no update available at this time. So, all in all 👍.

<img width="1498" alt="image" src="https://user-images.githubusercontent.com/35113775/223564726-aab53ddb-f98a-42f8-baf9-41d0a514296f.png">

**Comment by phillxnet** [comment]
@Hooverdan96 Re:

> However, I am happy to report that after a reboot of the system, it now shows correctly

Thanks for the follow-up here. Yes, this is likely due to older code still in play. Likely if you refreshed the front page it would have worked there-after on re-visiting the updates page. But all good I think and it does look to return us to what we had prior to the multi-repo work. Still, I'd like to add some unit testing on this procedure as there is non currently. However as mentioned in another thread this could be done during the pending clean-up where we drop the older yum compatibilities.

**Comment by kanecko** [comment]
Confirming what @Hooverdan96 said.
After upgrade: bug still there.
After restarting rockstor services: bug no longer present.
